carbon_cloud:
  mysql_address: localhost
  redis_address: localhost
  mongo_address: localhost
  eureka_address: localhost
server:
  port: 8086
info:
  groupId: @project.groupId@
  artifactId: @project.artifactId@
  version: @project.version@
spring:
  #profiles defined
  profiles:
    active: dev
  application:
    name: CarbonFace
eureka:
  instance:
    hostname: carbonface
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://${carbon_cloud.eureka_address}:8008/eureka/
